import type { SkillDefinition, WorkflowDefinition } from '@cogentrex/shared';

export const skillDefinitions: SkillDefinition[] = [
  {
    id: 'chat-general',
    label: 'General Chat',
    workflowId: 'CHAT',
    description: 'General conversation, reasoning, and artifact drafting.',
    requiredProviderCapabilities: ['text'],
    optionalProviderCapabilities: ['streaming', 'vision', 'tool-calling'],
    requiredToolCapabilities: [],
    optionalToolCapabilities: [],
    systemPromptModule: 'chat/default',
  },
  {
    id: 'image-prompt-default',
    label: 'Image Prompting',
    workflowId: 'IMAGE_GENERATION',
    description: 'Prompt-driven image generation and editing.',
    requiredProviderCapabilities: ['image'],
    optionalProviderCapabilities: ['vision'],
    requiredToolCapabilities: [],
    optionalToolCapabilities: [],
    systemPromptModule: 'media/image-default',
  },
  {
    id: 'social-writing-default',
    label: 'Social Writing',
    workflowId: 'SOCIAL_WRITING',
    description: 'Draft social posts from a user prompt, optional research, URLs, and images.',
    requiredProviderCapabilities: ['text'],
    optionalProviderCapabilities: ['vision'],
    requiredToolCapabilities: [],
    optionalToolCapabilities: ['web.search', 'web.fetch'],
    systemPromptModule: 'social/default',
  },
  {
    id: 'deep-research-default',
    label: 'Deep Research',
    workflowId: 'DEEP_RESEARCH',
    description: 'Plan searches, collect sources, and synthesize cited answers.',
    requiredProviderCapabilities: ['text'],
    optionalProviderCapabilities: ['streaming'],
    requiredToolCapabilities: ['web.search'],
    optionalToolCapabilities: ['web.fetch'],
    systemPromptModule: 'research/default',
  },
];

export const workflowDefinitions: WorkflowDefinition[] = [
  {
    id: 'CHAT',
    label: 'Chat',
    description: 'General AI conversation and artifact drafting.',
    requiredProviderCapabilities: ['text'],
    optionalProviderCapabilities: ['streaming', 'vision', 'tool-calling'],
    requiredToolCapabilities: [],
    optionalToolCapabilities: [],
    defaultSkillId: 'chat-general',
  },
  {
    id: 'IMAGE_GENERATION',
    label: 'Image Generation',
    description: 'Generate and edit images from prompts.',
    requiredProviderCapabilities: ['image'],
    optionalProviderCapabilities: ['vision'],
    requiredToolCapabilities: [],
    optionalToolCapabilities: [],
    defaultSkillId: 'image-prompt-default',
  },
  {
    id: 'SOCIAL_WRITING',
    label: 'Social Writing',
    description: 'Draft posts with optional research, URLs, and images.',
    requiredProviderCapabilities: ['text'],
    optionalProviderCapabilities: ['vision'],
    requiredToolCapabilities: [],
    optionalToolCapabilities: ['web.search', 'web.fetch'],
    defaultSkillId: 'social-writing-default',
  },
  {
    id: 'DEEP_RESEARCH',
    label: 'Deep Research',
    description: 'Plan, search, collect sources, and synthesize cited answers.',
    requiredProviderCapabilities: ['text'],
    optionalProviderCapabilities: ['streaming'],
    requiredToolCapabilities: ['web.search'],
    optionalToolCapabilities: ['web.fetch'],
    defaultSkillId: 'deep-research-default',
  },
];
